# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SAMM <- function(Y, X, Zlist, Klist, lambda, W, R, Siglist, corfunc, corfuncfixed, sigfunc, mmalg, tolparconv = 1e-10, tolparinv = 1e-10, maxiter = 1000L, geterrors = FALSE, Hinv = FALSE) {
    .Call('SAMM_SAMM', PACKAGE = 'SAMM', Y, X, Zlist, Klist, lambda, W, R, Siglist, corfunc, corfuncfixed, sigfunc, mmalg, tolparconv, tolparinv, maxiter, geterrors, Hinv)
}

ar1cov_cppforR <- function(params, data) {
    .Call('SAMM_ar1cov_cppforR', PACKAGE = 'SAMM', params, data)
}

ar1hetcov_cppforR <- function(params, data) {
    .Call('SAMM_ar1hetcov_cppforR', PACKAGE = 'SAMM', params, data)
}

arma11cov_cppforR <- function(params, data) {
    .Call('SAMM_arma11cov_cppforR', PACKAGE = 'SAMM', params, data)
}

compsymmcov_cppforR <- function(params, data) {
    .Call('SAMM_compsymmcov_cppforR', PACKAGE = 'SAMM', params, data)
}

compsymmhetcov_cppforR <- function(params, data) {
    .Call('SAMM_compsymmhetcov_cppforR', PACKAGE = 'SAMM', params, data)
}

lincombcov_cppforR <- function(params, data) {
    .Call('SAMM_lincombcov_cppforR', PACKAGE = 'SAMM', params, data)
}

unstrcov_cppforR <- function(params, data) {
    .Call('SAMM_unstrcov_cppforR', PACKAGE = 'SAMM', params, data)
}

diagcov_cppforR <- function(params, data) {
    .Call('SAMM_diagcov_cppforR', PACKAGE = 'SAMM', params, data)
}

unstrKronKcov_cppforR <- function(params, data) {
    .Call('SAMM_unstrKronKcov_cppforR', PACKAGE = 'SAMM', params, data)
}

diagKronKcov_cppforR <- function(params, data) {
    .Call('SAMM_diagKronKcov_cppforR', PACKAGE = 'SAMM', params, data)
}

ar1KronKcov_cppforR <- function(params, data) {
    .Call('SAMM_ar1KronKcov_cppforR', PACKAGE = 'SAMM', params, data)
}

ar1hetKronKcov_cppforR <- function(params, data) {
    .Call('SAMM_ar1hetKronKcov_cppforR', PACKAGE = 'SAMM', params, data)
}

arma11KronKcov_cppforR <- function(params, data) {
    .Call('SAMM_arma11KronKcov_cppforR', PACKAGE = 'SAMM', params, data)
}

compsymmKronKcov_cppforR <- function(params, data) {
    .Call('SAMM_compsymmKronKcov_cppforR', PACKAGE = 'SAMM', params, data)
}

compsymmhetKronKcov_cppforR <- function(params, data) {
    .Call('SAMM_compsymmhetKronKcov_cppforR', PACKAGE = 'SAMM', params, data)
}

UnstrKronUnstrcov_cppforR <- function(params, data) {
    .Call('SAMM_UnstrKronUnstrcov_cppforR', PACKAGE = 'SAMM', params, data)
}

rbfcov_cppforR <- function(params, data) {
    .Call('SAMM_rbfcov_cppforR', PACKAGE = 'SAMM', params, data)
}

expcov_cppforR <- function(params, data) {
    .Call('SAMM_expcov_cppforR', PACKAGE = 'SAMM', params, data)
}

rbfdistcov_cppforR <- function(params, data) {
    .Call('SAMM_rbfdistcov_cppforR', PACKAGE = 'SAMM', params, data)
}

expdistcov_cppforR <- function(params, data) {
    .Call('SAMM_expdistcov_cppforR', PACKAGE = 'SAMM', params, data)
}

relmatcov_cppforR <- function(params, data) {
    .Call('SAMM_relmatcov_cppforR', PACKAGE = 'SAMM', params, data)
}

ConstMatcov_cppforR <- function(params, data) {
    .Call('SAMM_ConstMatcov_cppforR', PACKAGE = 'SAMM', params, data)
}

KKronunstrcov_cppforR <- function(params, data) {
    .Call('SAMM_KKronunstrcov_cppforR', PACKAGE = 'SAMM', params, data)
}

KKrondiagcov_cppforR <- function(params, data) {
    .Call('SAMM_KKrondiagcov_cppforR', PACKAGE = 'SAMM', params, data)
}

KKronar1cov_cppforR <- function(params, data) {
    .Call('SAMM_KKronar1cov_cppforR', PACKAGE = 'SAMM', params, data)
}

KKronar1hetcov_cppforR <- function(params, data) {
    .Call('SAMM_KKronar1hetcov_cppforR', PACKAGE = 'SAMM', params, data)
}

KKronarma11cov_cppforR <- function(params, data) {
    .Call('SAMM_KKronarma11cov_cppforR', PACKAGE = 'SAMM', params, data)
}

KKroncompsymmcov_cppforR <- function(params, data) {
    .Call('SAMM_KKroncompsymmcov_cppforR', PACKAGE = 'SAMM', params, data)
}

KKroncompsymmhetcov_cppforR <- function(params, data) {
    .Call('SAMM_KKroncompsymmhetcov_cppforR', PACKAGE = 'SAMM', params, data)
}

sppowcov_cppforR <- function(params, data) {
    .Call('SAMM_sppowcov_cppforR', PACKAGE = 'SAMM', params, data)
}

splincov_cppforR <- function(params, data) {
    .Call('SAMM_splincov_cppforR', PACKAGE = 'SAMM', params, data)
}

splinlogcov_cppforR <- function(params, data) {
    .Call('SAMM_splinlogcov_cppforR', PACKAGE = 'SAMM', params, data)
}

diagSig_cppforR <- function(params, data) {
    .Call('SAMM_diagSig_cppforR', PACKAGE = 'SAMM', params, data)
}

IdentSig_cppforR <- function(params, data) {
    .Call('SAMM_IdentSig_cppforR', PACKAGE = 'SAMM', params, data)
}

UnstrKronIdentSig_cppforR <- function(params, data) {
    .Call('SAMM_UnstrKronIdentSig_cppforR', PACKAGE = 'SAMM', params, data)
}

IdentKronUnstrSig_cppforR <- function(params, data) {
    .Call('SAMM_IdentKronUnstrSig_cppforR', PACKAGE = 'SAMM', params, data)
}

FA1hetSig_cppforR <- function(params, data) {
    .Call('SAMM_FA1hetSig_cppforR', PACKAGE = 'SAMM', params, data)
}

FA1homSig_cppforR <- function(params, data) {
    .Call('SAMM_FA1homSig_cppforR', PACKAGE = 'SAMM', params, data)
}

compsymmhomSig_cppforR <- function(params, data) {
    .Call('SAMM_compsymmhomSig_cppforR', PACKAGE = 'SAMM', params, data)
}

compsymmhetSig_cppforR <- function(params, data) {
    .Call('SAMM_compsymmhetSig_cppforR', PACKAGE = 'SAMM', params, data)
}

FAhetSig_cppforR <- function(params, data) {
    .Call('SAMM_FAhetSig_cppforR', PACKAGE = 'SAMM', params, data)
}

FAhomSig_cppforR <- function(params, data) {
    .Call('SAMM_FAhomSig_cppforR', PACKAGE = 'SAMM', params, data)
}

